name: Clubs Team
description: Place for helping the leaders of Hack Clubs
maintainers: [thomas, arpan, sahiti, jasper, sarah]
channels:
  - name: leaders
    id: C02PA5G01ND
    notify: [sarah]
  - name: application-conspiracy
    id: C02F9GD407J
    notify: [sarah, jasper]
  - name: the-clubhouse
    id: C06TK8S9L3V
    notify: [sarah, jasper]
repos:
  - uri: https://github.com/hackclub/jams
    # notify: [jasper]
  - uri: https://github.com/hackclub/toolbox
    # notify: [jasper]
  - uri: https://github.com/hackclub/workshops
    # notify: [jasper]
  - uri: https://github.com/hackclub/application-viewer
    notify: [jasper]
  - uri: https://github.com/hackclub/apply
    notify: [jasper]
  - uri: https://github.com/hackclub/turnover
    notify: [jasper]
