name: DNS
description: DNS stuff for Hack Club
maintainers: [faisal, graham, sam, max, caleb, sean]
channels:
  - name: dns
    id: CS8TQ86GN
    sla:
      responseTime: 1h
repos:
  - uri: https://github.com/hackclub/dns
    sla:
      responseTime: 1h
resources:
  - name: github
    uri: https://github.com/hackclub/dns
