name: Sprig
description: Teens make games and get a Sprig
maintainers: [lucas, graham, josias, shawn, shubham, faisal, marios, savina]
channels:
  - name: sprig
    id: C02UN35M7LG
    grouping:
      minutes: 10
  - name: sprig-stuck-requests
    id: C06L5SNPPL6
  - name: sprig-platform
    id: C04S1A8NT44
    grouping:
      minutes: 10
  - name: sprig-device-requests
    id: C063DFZ532M
repos:
  - uri: https://github.com/hackclub/sprig
  - uri: https://github.com/hackclub/spade
resources:
  - name: github-sprig-editor
    uri: https://github.com/hackclub/sprig
  - name: github-sprig-engine
    uri: https://github.com/hackclub/sprig-engine
  - name: github-firmware
    uri: https://github.com/hackclub/spade
  - name: dashboard
    uri: https://telemetry.hackclub.com/d/b7ac7960-a18f-4c83-a4e5-767d50ad62c7/sprig?orgId=1
  - name: vercel
    uri: https://vercel.com/hackclub/sprig
  - name: website
    uri: https://sprig.hackclub.com
  - name: editor
    uri: https://sprig.hackclub.com/editor
sections:
  - name: games
    pattern: What is your game about
  - name: help
    pattern: help
  - name: devices
    pattern: A new Sprig device has been requested
  - name: devices-india
    pattern: A new Sprig device *in India* has been requested
  - name: stuck
    pattern: got stuck in Sprig
