name: Welcomers
description: A group of people that give warm welcomes to new Hack Clubbers!
maintainers: [arav, toby, chris, faisal, dev, thomas, arpan, sahiti, gaurav, jasper, karmanyaah, kaleo, alex, zoya, shubhampatil, khaleel]
channels:
  - name: welcome-committee
    id: GLFAEL1SL
  - name: welcome
    id: C75M7C0SY
resources:
 - name: welcomers-leaderboard
    uri: https://welcomers-leaderboard.hackclub.dev/
  - name: welcome-scripts
    uri: https://hackclub.slack.com/docs/T0266FRGM/F054X091EG2
repos: []
