name: You Ship We Ship
description: Centralized You Ship We Ship for Hack Clubbers
maintainers: [faisal, graham]
channels:
  - name: verification-requests
    id: C06TP6YPWKC
    notify: [faisal, graham]
  - name: ysws-submissions
    id: C06U25JH0E5
    notify: [graham]
    
repos: []
sections:
  - name: verify
    pattern: A new verification request has been submitted
  - name: projects
    pattern: A new YSWS project has been submitted
